version: '3.7'
services:
    dummy-sensor:
        image: itfitz.com.au/dummy-sensor/dummy-sensor:2.0.0-beta
        # ports:
        #     - "9999:9999"
        volumes:
            - dummy-sensor-storage:./storage

volumes:
    dummy-sensor-storage::