version: '3.7'
services:
    dummy-sensor:
        build: 
            context: .
            args:
                mqtt_topic: 'topic/dummy-sensor'
                mqtt_hostname: 'mosquitto'
                mqtt_port: 1883
                count: -1
                interval: 10
        container_name: dummy-sensor
        depends_on:
            - mqtt
        networks:
            - default

    mqtt:
        image: eclipse-mosquitto
        container_name: mosquitto
        expose:
            - "1883"
        ports:
            - "1883:1883"
        networks:
            - default

networks:
    default:
        external:
            name: influx-test_default
